version: '3'

services:
  backend:
    build: 
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/user/src/backend
    ports:
      - "8000:8000"
    env_file:
      - ./ .env.dev
    depends_on:
      - psql_db

  psql_db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=badsha
      - POSTGRES_DB=vendor_db

volumes:
  postgres_data:
